apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: loki
    release: loki
  name: storage-loki-alert
  namespace: monitoring

spec:
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /
    type: Directory
  capacity:
    storage: 2Gi
  volumeMode: Filesystem