apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: {{ .Values.containers.image_nginx }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/serv-nginx.conf
              subPath: serv-nginx.conf
            - name: index
              mountPath: /var/www/html/index.html
              subPath: index.html
         # readinessProbe:
         #   httpGet:
         #     scheme: HTTP
         #     path: /index.html
         #     port: 80
         #   initialDelaySeconds: 10
         #   periodSeconds: 5
         # livenessProbe:
         #   httpGet:
         #     scheme: HTTP
         #     path: /index.html
         #     port: 80
         #   initialDelaySeconds: 10
         #   periodSeconds: 5
         # startupProbe:
         #   httpGet:
         #     scheme: HTTP
         #     path: /index.html
         #     port: 80
         #   initialDelaySeconds: 10
         #   periodSeconds: 5

        - name: apache
          image: {{ .Values.containers.image_apache }}
          ports:
            - containerPort: 8000
      volumes:
        - name: config
          secret:
            secretName: nginx-config
        - name: index
          configMap:
            name: index-config
