apiVersion: argoproj.io/v2alpha1
kind: Application
metadata:
  name: nginx-app-argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

source:
  repoURL: https://github.com/gghh23/k8s.git
  targetRevision: HEAD
  path: t31-ArgoCD
destination:
  server: https://kubernets.default.svc
  namespace: argocd

syncPolicy:
  syncOptions:
    - CreateNamespace=true
  automated:
    selfHeal: true
    prune: true
