apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
project: default
source:
  repoURL: 'https://github.com/gghh23/k8s.git'
  path: t31-ArgoCD/chart
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default


