apiVersion: v1 
kind: Service
metadata: 
 name: gop-fs-service 
spec:
 type: NodePort
 ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31200
 selector:
  run: gop-file-server

---

apiVersion: v1
kind: Pod
metadata:
 name: gop-file-server
 labels:
  run: gop-file-server
spec:
 containers:
 - name: gop-file-server
   image: kodekloud/fileserver
   volumeMounts:
   - mountPath: /web
     name: data-store 
 volumes: 
 - name: data-store 
   persistentVolumeClaim:
    claimName: data-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: data-pvc
spec: 
 accessModes: ["ReadWriteMany"]
 volumeName: data-pv
 resources:
    requests:
      storage: 1Gi
 
---

apiVersion: v1 
kind: PersistentVolume
metadata:
 name: data-pv
spec:
 accessModes: ["ReadWriteMany"]
 hostPath: 
  path: /web
  type: Directory
 capacity: 
    storage: 1Gi
