apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: aws-cluster
  region: us-east-1

vpc:
  id: 

managedNodeGroups:
- name: worker-node
  desiredCapacity: 1
  instanceType: "t3.large"
